### ISSUE TITLE
"Making all in demo" ends with error: "configure.ac:24: error: m4_defn: undefined macro: _m4_divert_diversion"

### ISSUE THREAD

**Issue by ligaard** [sorced-jim/SPDY-for-iPhone#1]
I tried doing compiling as described in the readme. When it reached the "Making all in demo" part, it errored out; see details below.

Making all in demo
gcc -DHAVE_CONFIG_H -I. -I../src    `pkg-config --cflags check` -I../include -g -O2 -MT server.o -MD -MP -MF .deps/server.Tpo -c -o server.o server.c
/bin/sh: pkg-config: command not found
mv -f .deps/server.Tpo .deps/server.Po
/bin/sh ../libtool --tag=CC   --mode=link gcc `pkg-config --cflags check` -I../include -g -O2 `pkg-config --libs check` `pkg-config --libs zlib`  -o server server.o ../src/libspdy.la 
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
libtool: link: gcc -I../include -g -O2 -o .libs/server server.o  ../src/.libs/libspdy.dylib
gcc -DHAVE_CONFIG_H -I. -I../src    `pkg-config --cflags check` -I../include -g -O2 -MT client.o -MD -MP -MF .deps/client.Tpo -c -o client.o client.c
/bin/sh: pkg-config: command not found
mv -f .deps/client.Tpo .deps/client.Po
/bin/sh ../libtool --tag=CC   --mode=link gcc `pkg-config --cflags check` -I../include -g -O2 `pkg-config --libs check` `pkg-config --libs zlib`  -o client client.o ../src/libspdy.la 
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
libtool: link: gcc -I../include -g -O2 -o .libs/client client.o  ../src/.libs/libspdy.dylib
make[2]: Nothing to be done for `all-am'.
cd spdylay && autoreconf -i && automake && autoconf
configure.ac:24: error: m4_defn: undefined macro: _m4_divert_diversion
configure.ac:24: the top level
autom4te: /usr/bin/gm4 failed with exit status: 1
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
make: **\* [spdylay/configure] Error 1

**Comment by sorced-jim** [comment]
I've done two things to make this easier.  First, I've explicitly listed
pkgconfig, et all in the README file as needed to build.  Second,
I've removed spindly since it's not being used.   spdylay still needs
pkg-config though.

On Thu, Feb 9, 2012 at 11:25 AM, Kasper Ligaard <
reply@reply.github.com

> wrote:
> 
> I tried doing compiling as described in the readme. When it reached the
> "Making all in demo" part, it errored out; see details below.
> 
> Making all in demo
> gcc -DHAVE_CONFIG_H -I. -I../src    `pkg-config --cflags check`
> -I../include -g -O2 -MT server.o -MD -MP -MF .deps/server.Tpo -c -o
> server.o server.c
> /bin/sh: pkg-config: command not found
> mv -f .deps/server.Tpo .deps/server.Po
> /bin/sh ../libtool --tag=CC   --mode=link gcc `pkg-config --cflags check`
> -I../include -g -O2 `pkg-config --libs check` `pkg-config --libs zlib`  -o
> server server.o ../src/libspdy.la
> /bin/sh: pkg-config: command not found
> /bin/sh: pkg-config: command not found
> /bin/sh: pkg-config: command not found
> libtool: link: gcc -I../include -g -O2 -o .libs/server server.o
>  ../src/.libs/libspdy.dylib
> gcc -DHAVE_CONFIG_H -I. -I../src    `pkg-config --cflags check`
> -I../include -g -O2 -MT client.o -MD -MP -MF .deps/client.Tpo -c -o
> client.o client.c
> /bin/sh: pkg-config: command not found
> mv -f .deps/client.Tpo .deps/client.Po
> /bin/sh ../libtool --tag=CC   --mode=link gcc `pkg-config --cflags check`
> -I../include -g -O2 `pkg-config --libs check` `pkg-config --libs zlib`  -o
> client client.o ../src/libspdy.la
> /bin/sh: pkg-config: command not found
> /bin/sh: pkg-config: command not found
> /bin/sh: pkg-config: command not found
> libtool: link: gcc -I../include -g -O2 -o .libs/client client.o
>  ../src/.libs/libspdy.dylib
> make[2]: Nothing to be done for `all-am'.
> cd spdylay && autoreconf -i && automake && autoconf
> configure.ac:24: error: m4_defn: undefined macro: _m4_divert_diversion
> configure.ac:24: the top level
> autom4te: /usr/bin/gm4 failed with exit status: 1
> aclocal: /usr/bin/autom4te failed with exit status: 1
> autoreconf: aclocal failed with exit status: 1
> make: **\* [spdylay/configure] Error 1
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sorced-jim/SPDY-for-iPhone/issues/1

## 

Jim
https://twitter.com/#!/sorced_eng
