### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by coolstar** [sorced-jim/SPDY-for-iPhone#6]
When trying to run the demo app SPDY-demo, I get an EXC_BAD_ACCESS when trying to connect to any SPDY enabled website.
I'm using XCode 4.2 with iOS 5 SDK on Snow Leopard.

**Comment by sorced-jim** [comment]
Thanks for the bug report.   I should have time Thursday or Friday to look
at this issue.
On Jul 16, 2012 5:49 PM, "coolstar" <
reply@reply.github.com>
wrote:

**Comment by coolstar** [comment]
Hello, are you going to look at this issue?

**Comment by sorced-jim** [comment]
Finally I have time, work got a bit busy getting our next release out.

On Tue, Jul 31, 2012 at 1:27 AM, coolstar <
reply@reply.github.com

> wrote:
> 
> Hello, are you going to look at this issue?
> 
> On Jul 17, 2012, at 8:04 PM, sorced-jimreply@reply.github.com wrote:
> 
> > Thanks for the bug report.   I should have time Thursday or Friday to
> > look
> > at this issue.
> > On Jul 16, 2012 5:49 PM, "coolstar" <
> > reply@reply.github.com>
> > wrote:
> > 
> > > When trying to run the demo app SPDY-demo, I get an EXC_BAD_ACCESS when
> > > trying to connect to any SPDY enabled website.
> > > I'm using XCode 4.2 with iOS 5 SDK on Snow Leopard.
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/sorced-jim/SPDY-for-iPhone/issues/6
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/sorced-jim/SPDY-for-iPhone/issues/6#issuecomment-7055525
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sorced-jim/SPDY-for-iPhone/issues/6#issuecomment-7392415

## 

Jim
https://twitter.com/#!/sorced_eng

**Comment by sorced-jim** [comment]
Fixed in https://github.com/sorced-jim/SPDY-for-iPhone/commit/a0050c6308170a9b46c6e5e106176ef4b43bacae .
