### ISSUE TITLE
SPDY caching

### ISSUE THREAD

**Issue by markabey** [sorced-jim/SPDY-for-iPhone#7]
The issue is that, when a request using SPDY finishes loading, the response is not presented to the shared URL cache for storage. 

This is likely due to the following line in SpdyUrlConnection.m (in onResponseHeaders:)

``` objectivec
[[self.protocol client] URLProtocol:self.protocol didReceiveResponse:response cacheStoragePolicy:NSURLCacheStorageNotAllowed];
```

(I'm not sure whether the problem could be fixed by just allowing cache storage here, or whether this would lead to other SPDY-related problems…)

**Comment by sorced-jim** [comment]
I changed it to use NSURLCacheStorageAllowed .
